version: '3'

services:
  dev:
    image: gerhardlr/tango_python:latest
    container_name: dev
    volumes:
      - $DEV_HOME:/app
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - FLASK_APP=deviceWrapper
      - FLASK_DEBUG=true
    expose:
      - "5002"
    ports:
      - "127.0.0.1:5002:5000"
    #command: bash -c "flask run --host=0.0.0.0"
    networks:
      - default
networks:
  default:
    external:
      name: DOCKER_NETWORK